#########################################################################
# pgNetworks - Tools for filtering and parsing osm data
#
# Build instructions for an osmium docker image
# During build there's a lot of cruft that doesn't do productive work
# That's why compiling is done in a first stage
# and the built sources are then copied to a second runner stage
#
# build image with: docker build -t pgnetworks:osmium .
# remove image with: docker rmi pgnetworks:osmium
# run the container with shell attached: docker run -ti pgnetworks:osmium
# list images: docker image list

######################################
#   Stage 1 - build osmium from source
#


FROM debian:latest as builder

WORKDIR .


# Specify the release versions for the build

ENV OSMIUM_VERSION 2.20.0
ENV OSMIUM_TOOL_VERSION 1.16.0
ENV PROTOZERO_VERSION 1.6.3


# update the sytem and install relevant dependencies / packages

RUN apt-get update && apt-get upgrade && apt-get install -y \
    wget \
    rapidjson-dev \
    libboost-program-options-dev \
    libbz2-dev \
    zlib1g-dev \
    liblz4-dev \
    libexpat1-dev \
    cmake \
    pandoc \
    libboost-dev \ 
    libgdal-dev \
    libproj-dev \
    doxygen \
    graphviz \
    g++ 


# Download the version specific code sources and create build directory

RUN <<EOF

    mkdir /var/osmium_builder

    wget https://github.com/osmcode/libosmium/archive/v${OSMIUM_VERSION}.tar.gz && \
    tar xzvf v${OSMIUM_VERSION}.tar.gz && \
    rm v${OSMIUM_VERSION}.tar.gz && \
    mv libosmium-${OSMIUM_VERSION} libosmium

    wget https://github.com/osmcode/osmium-tool/archive/v${OSMIUM_TOOL_VERSION}.tar.gz && \
    tar xzvf v${OSMIUM_TOOL_VERSION}.tar.gz && \
    rm v${OSMIUM_TOOL_VERSION}.tar.gz && \
    mv osmium-tool-${OSMIUM_TOOL_VERSION} osmium-tool

    wget https://github.com/mapbox/protozero/archive/v${PROTOZERO_VERSION}.tar.gz && \
    tar xzvf v${PROTOZERO_VERSION}.tar.gz && \
    rm v${PROTOZERO_VERSION}.tar.gz && \
    mv protozero-${PROTOZERO_VERSION} protozero

EOF

# Build osmium

RUN <<EOF 

    cd osmium-tool && mkdir build 
    cd build 
    cmake ..
    make
    ctest --output-on-failure
    make install

EOF


# Collect the installed files into a tar archive for use in stage 2

RUN find /usr/local -name "osmium*" -exec tar -rvPf /var/osmium_builder/osmium.tar {} + 


################################################
#   Stage 2 - install osmium on the runner image
#

FROM debian:latest
LABEL org.opencontainers.image.authors="matthias.daues@datenschoenheit.de"


# Define the working directory for the runner stage

WORKDIR .


# Copy osmium to the runner stage

COPY --from=builder /var/osmium_builder/osmium.tar ./osmium.tar
RUN tar xPf ./osmium.tar


# Install dependencies im runner stage

RUN apt-get update && apt-get upgrade && apt-get install -y \
    libboost-program-options-dev


# Clean up

RUN apt clean && rm -rf /var/lib/apt/lists/*